// Code generated by "mx generate". DO NOT EDIT.
//go:build !ignoreMXGen

package frontend

import (
	"context"
	"github.com/sh3lk/mx"
	"github.com/sh3lk/mx/runtime/codegen"
	"go.opentelemetry.io/otel/trace"
	"reflect"
)

func init() {
	codegen.Register(codegen.Registration{
		Name:      "github.com/sh3lk/mx/Main",
		Iface:     reflect.TypeOf((*mx.Main)(nil)).Elem(),
		Impl:      reflect.TypeOf(server{}),
		Listeners: []string{"bank"},
		LocalStubFn: func(impl any, caller string, tracer trace.Tracer) any {
			return main_local_stub{impl: impl.(mx.Main), tracer: tracer}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any { return main_client_stub{stub: stub} },
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return main_server_stub{impl: impl.(mx.Main), addLoad: addLoad}
		},
		ReflectStubFn: func(caller func(string, context.Context, []any, []any) error) any {
			return main_reflect_stub{caller: caller}
		},
		RefData: "⟦583f439b:MxEdge:github.com/sh3lk/mx/Main→github.com/sh3lk/mx/examples/bankofanthos/balancereader/T⟧\n⟦01efa328:MxEdge:github.com/sh3lk/mx/Main→github.com/sh3lk/mx/examples/bankofanthos/contacts/T⟧\n⟦285db949:MxEdge:github.com/sh3lk/mx/Main→github.com/sh3lk/mx/examples/bankofanthos/ledgerwriter/T⟧\n⟦c236fa3b:MxEdge:github.com/sh3lk/mx/Main→github.com/sh3lk/mx/examples/bankofanthos/transactionhistory/T⟧\n⟦0906345d:MxEdge:github.com/sh3lk/mx/Main→github.com/sh3lk/mx/examples/bankofanthos/userservice/T⟧\n⟦969790bc:wEaVeRlIsTeNeRs:github.com/sh3lk/mx/Main→bank⟧\n",
	})
}

// mx.InstanceOf checks.
var _ mx.InstanceOf[mx.Main] = (*server)(nil)

// mx.Router checks.
var _ mx.Unrouted = (*server)(nil)

// Local stub implementations.

type main_local_stub struct {
	impl   mx.Main
	tracer trace.Tracer
}

// Check that main_local_stub implements the mx.Main interface.
var _ mx.Main = (*main_local_stub)(nil)

// Client stub implementations.

type main_client_stub struct {
	stub codegen.Stub
}

// Check that main_client_stub implements the mx.Main interface.
var _ mx.Main = (*main_client_stub)(nil)

// Note that "mx generate" will always generate the error message below.
// Everything is okay. The error message is only relevant if you see it when
// you run "go build" or "go run".
var _ codegen.LatestVersion = codegen.Version[[0][24]struct{}](`

ERROR: You generated this file with 'mx generate' (devel) (codegen
version v0.24.0). The generated code is incompatible with the version of the
github.com/sh3lk/mx module that you're using. The mx module
version can be found in your go.mod file or by running the following command.

    go list -m github.com/sh3lk/mx

We recommend updating the mx module and the 'mx generate' command by
running the following.

    go get github.com/sh3lk/mx@latest
    go install github.com/sh3lk/mx/cmd/mx@latest

Then, re-run 'mx generate' and re-build your code. If the problem persists,
please file an issue at https://github.com/sh3lk/mx/issues.

`)

// Server stub implementations.

type main_server_stub struct {
	impl    mx.Main
	addLoad func(key uint64, load float64)
}

// Check that main_server_stub implements the codegen.Server interface.
var _ codegen.Server = (*main_server_stub)(nil)

// GetStubFn implements the codegen.Server interface.
func (s main_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	default:
		return nil
	}
}

// Reflect stub implementations.

type main_reflect_stub struct {
	caller func(string, context.Context, []any, []any) error
}

// Check that main_reflect_stub implements the mx.Main interface.
var _ mx.Main = (*main_reflect_stub)(nil)
