[mx]
binary = "./collatz"
args = ["--local_addr=localhost:10000"]
rollout = "5m"
colocate = [
  [
    "main",
    "github.com/sh3lk/mx/examples/collatz/Even",
    "github.com/sh3lk/mx/examples/collatz/Odd"
  ]
]

[ssh]
locations = "./ssh_locations.txt"

[gke]
regions = ["us-west1"]
listeners.collatz = {is_public = true, hostname = "collatz.example.com"}
