// Code generated by "mx generate". DO NOT EDIT.
//go:build !ignoreMXGen

package model

import (
	"fmt"
	"github.com/sh3lk/mx"
	"github.com/sh3lk/mx/runtime/codegen"
	"time"
)

// mx.InstanceOf checks.

// mx.Router checks.

// Local stub implementations.

// Client stub implementations.

// Note that "mx generate" will always generate the error message below.
// Everything is okay. The error message is only relevant if you see it when
// you run "go build" or "go run".
var _ codegen.LatestVersion = codegen.Version[[0][24]struct{}](`

ERROR: You generated this file with 'mx generate' (devel) (codegen
version v0.24.0). The generated code is incompatible with the version of the
github.com/sh3lk/mx module that you're using. The mx module
version can be found in your go.mod file or by running the following command.

    go list -m github.com/sh3lk/mx

We recommend updating the mx module and the 'mx generate' command by
running the following.

    go get github.com/sh3lk/mx@latest
    go install github.com/sh3lk/mx/cmd/mx@latest

Then, re-run 'mx generate' and re-build your code. If the problem persists,
please file an issue at https://github.com/sh3lk/mx/issues.

`)

// Server stub implementations.

// Reflect stub implementations.

// AutoMarshal implementations.

var _ codegen.AutoMarshal = (*Transaction)(nil)

type __is_Transaction[T ~struct {
	mx.AutoMarshal
	FromAccountNum string    "gorm:\"column:from_acct;not null\""
	FromRoutingNum string    "gorm:\"column:from_route;not null\""
	ToAccountNum   string    "gorm:\"column:to_acct;not null\""
	ToRoutingNum   string    "gorm:\"column:to_route;not null\""
	Amount         int64     "gorm:\"column:amount;not null\""
	Timestamp      time.Time "gorm:\"column:timestamp;not null\""
}] struct{}

var _ __is_Transaction[Transaction]

func (x *Transaction) MXMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("Transaction.MXMarshal: nil receiver"))
	}
	enc.String(x.FromAccountNum)
	enc.String(x.FromRoutingNum)
	enc.String(x.ToAccountNum)
	enc.String(x.ToRoutingNum)
	enc.Int64(x.Amount)
	enc.EncodeBinaryMarshaler(&x.Timestamp)
}

func (x *Transaction) MXUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("Transaction.MXUnmarshal: nil receiver"))
	}
	x.FromAccountNum = dec.String()
	x.FromRoutingNum = dec.String()
	x.ToAccountNum = dec.String()
	x.ToRoutingNum = dec.String()
	x.Amount = dec.Int64()
	dec.DecodeBinaryUnmarshaler(&x.Timestamp)
}

var _ codegen.AutoMarshal = (*TransactionWithID)(nil)

type __is_TransactionWithID[T ~struct {
	mx.AutoMarshal
	Transaction
	TransactionID int64 "gorm:\"column:transaction_id;primaryKey;autoIncrement:true\""
}] struct{}

var _ __is_TransactionWithID[TransactionWithID]

func (x *TransactionWithID) MXMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("TransactionWithID.MXMarshal: nil receiver"))
	}
	(x.Transaction).MXMarshal(enc)
	enc.Int64(x.TransactionID)
}

func (x *TransactionWithID) MXUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("TransactionWithID.MXUnmarshal: nil receiver"))
	}
	(&x.Transaction).MXUnmarshal(dec)
	x.TransactionID = dec.Int64()
}
